In [495]:
import polars as pl
import pandas as pd
import numpy as np

In [496]:
matches=pl.read_csv(r"D:\Ravikumar\Git\ravikumar\statistics\testing\ipl\matches.csv")
matches

shape: (756, 18)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ match_id ┆ season ┆ city       ┆ date       ┆ … ┆ venue      ┆ umpire1   ┆ umpire2   ┆ umpire3   │
│ ---      ┆ ---    ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│ i64      ┆ i64    ┆ str        ┆ str        ┆   ┆ str        ┆ str       ┆ str       ┆ str       │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2017   ┆ Hyderabad  ┆ 2017-04-05 ┆ … ┆ Rajiv      ┆ AY        ┆ NJ Llong  ┆ null      │
│          ┆        ┆            ┆            ┆   ┆ Gandhi Int ┆ Dandekar  ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ ernational ┆           ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ Stadi…     ┆           ┆           ┆           │
│ 2        ┆ 2017   ┆ Pune       ┆ 2017-04-06 ┆ … ┆ Maharashtr ┆ A Nand    ┆ S Ravi    ┆ null      │
│          ┆        ┆            ┆            ┆   ┆ a Cricket  ┆ Kishore   ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ Associatio ┆           ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ n …        ┆           ┆           ┆           │
│ 3        ┆ 2017   ┆ Rajkot     ┆ 2017-04-07 ┆ … ┆ Saurashtra ┆ Nitin     ┆ CK Nandan ┆ null      │
│          ┆        ┆            ┆            ┆   ┆ Cricket    ┆ Menon     ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ Associatio ┆           ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ n S…       ┆           ┆           ┆           │
│ 4        ┆ 2017   ┆ Indore     ┆ 2017-04-08 ┆ … ┆ Holkar     ┆ AK        ┆ C Shamshu ┆ null      │
│          ┆        ┆            ┆            ┆   ┆ Cricket    ┆ Chaudhary ┆ ddin      ┆           │
│          ┆        ┆            ┆            ┆   ┆ Stadium    ┆           ┆           ┆           │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 11412    ┆ 2019   ┆ Chennai    ┆ 07/05/19   ┆ … ┆ M. A. Chid ┆ Nigel     ┆ Nitin     ┆ Ian Gould │
│          ┆        ┆            ┆            ┆   ┆ ambaram    ┆ Llong     ┆ Menon     ┆           │
│          ┆        ┆            ┆            ┆   ┆ Stadium    ┆           ┆           ┆           │
│ 11413    ┆ 2019   ┆ Visakhapat ┆ 08/05/19   ┆ … ┆ ACA-VDCA   ┆ null      ┆ null      ┆ null      │
│          ┆        ┆ nam        ┆            ┆   ┆ Stadium    ┆           ┆           ┆           │
│ 11414    ┆ 2019   ┆ Visakhapat ┆ 10/05/19   ┆ … ┆ ACA-VDCA   ┆ Sundaram  ┆ Bruce     ┆ Chettitho │
│          ┆        ┆ nam        ┆            ┆   ┆ Stadium    ┆ Ravi      ┆ Oxenford  ┆ dy Shamsh │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ uddin     │
│ 11415    ┆ 2019   ┆ Hyderabad  ┆ 12/05/19   ┆ … ┆ Rajiv      ┆ Nitin     ┆ Ian Gould ┆ Nigel     │
│          ┆        ┆            ┆            ┆   ┆ Gandhi     ┆ Menon     ┆           ┆ Llong     │
│          ┆        ┆            ┆            ┆   ┆ Intl.      ┆           ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ Cricket    ┆           ┆           ┆           │
│          ┆        ┆            ┆            ┆   ┆ Stadi…     ┆           ┆           ┆           │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [497]:
matches=matches.drop("season","player_of_match","umpire1","umpire2",'umpire3',"city","win_by_runs","win_by_wickets").filter(pl.col("dl_applied")==0)
matches

shape: (737, 10)
┌──────────┬────────────┬────────────┬────────────┬───┬────────┬──────────┬────────────┬───────────┐
│ match_id ┆ date       ┆ team1      ┆ team2      ┆ … ┆ result ┆ dl_appli ┆ winner     ┆ venue     │
│ ---      ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---    ┆ ed       ┆ ---        ┆ ---       │
│ i64      ┆ str        ┆ str        ┆ str        ┆   ┆ str    ┆ ---      ┆ str        ┆ str       │
│          ┆            ┆            ┆            ┆   ┆        ┆ i64      ┆            ┆           │
╞══════════╪════════════╪════════════╪════════════╪═══╪════════╪══════════╪════════════╪═══════════╡
│ 1        ┆ 2017-04-05 ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ normal ┆ 0        ┆ Sunrisers  ┆ Rajiv     │
│          ┆            ┆ Hyderabad  ┆ lengers    ┆   ┆        ┆          ┆ Hyderabad  ┆ Gandhi    │
│          ┆            ┆            ┆ Bangalore  ┆   ┆        ┆          ┆            ┆ Internati │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ onal      │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ Stadi…    │
│ 2        ┆ 2017-04-06 ┆ Mumbai     ┆ Rising     ┆ … ┆ normal ┆ 0        ┆ Rising     ┆ Maharasht │
│          ┆            ┆ Indians    ┆ Pune       ┆   ┆        ┆          ┆ Pune       ┆ ra        │
│          ┆            ┆            ┆ Supergiant ┆   ┆        ┆          ┆ Supergiant ┆ Cricket   │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ Associati │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ on …      │
│ 3        ┆ 2017-04-07 ┆ Gujarat    ┆ Kolkata    ┆ … ┆ normal ┆ 0        ┆ Kolkata    ┆ Saurashtr │
│          ┆            ┆ Lions      ┆ Knight     ┆   ┆        ┆          ┆ Knight     ┆ a Cricket │
│          ┆            ┆            ┆ Riders     ┆   ┆        ┆          ┆ Riders     ┆ Associati │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ on S…     │
│ 4        ┆ 2017-04-08 ┆ Rising     ┆ Kings XI   ┆ … ┆ normal ┆ 0        ┆ Kings XI   ┆ Holkar    │
│          ┆            ┆ Pune       ┆ Punjab     ┆   ┆        ┆          ┆ Punjab     ┆ Cricket   │
│          ┆            ┆ Supergiant ┆            ┆   ┆        ┆          ┆            ┆ Stadium   │
│ …        ┆ …          ┆ …          ┆ …          ┆ … ┆ …      ┆ …        ┆ …          ┆ …         │
│ 11412    ┆ 07/05/19   ┆ Chennai    ┆ Mumbai     ┆ … ┆ normal ┆ 0        ┆ Mumbai     ┆ M. A. Chi │
│          ┆            ┆ Super      ┆ Indians    ┆   ┆        ┆          ┆ Indians    ┆ dambaram  │
│          ┆            ┆ Kings      ┆            ┆   ┆        ┆          ┆            ┆ Stadium   │
│ 11413    ┆ 08/05/19   ┆ Sunrisers  ┆ Delhi      ┆ … ┆ normal ┆ 0        ┆ Delhi      ┆ ACA-VDCA  │
│          ┆            ┆ Hyderabad  ┆ Capitals   ┆   ┆        ┆          ┆ Capitals   ┆ Stadium   │
│ 11414    ┆ 10/05/19   ┆ Delhi      ┆ Chennai    ┆ … ┆ normal ┆ 0        ┆ Chennai    ┆ ACA-VDCA  │
│          ┆            ┆ Capitals   ┆ Super      ┆   ┆        ┆          ┆ Super      ┆ Stadium   │
│          ┆            ┆            ┆ Kings      ┆   ┆        ┆          ┆ Kings      ┆           │
│ 11415    ┆ 12/05/19   ┆ Mumbai     ┆ Chennai    ┆ … ┆ normal ┆ 0        ┆ Mumbai     ┆ Rajiv     │
│          ┆            ┆ Indians    ┆ Super      ┆   ┆        ┆          ┆ Indians    ┆ Gandhi    │
│          ┆            ┆            ┆ Kings      ┆   ┆        ┆          ┆            ┆ Intl.     │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ Cricket   │
│          ┆            ┆            ┆            ┆   ┆        ┆          ┆            ┆ Stadi…    │
└──────────┴────────────┴────────────┴────────────┴───┴────────┴──────────┴────────────┴───────────┘

In [498]:
matches=matches.filter(pl.col("result")=="normal").drop("result","dl_applied","date")
matches

shape: (724, 7)
┌──────────┬──────────────┬──────────────┬──────────────┬────────────┬──────────────┬──────────────┐
│ match_id ┆ team1        ┆ team2        ┆ toss_winner  ┆ toss_decis ┆ winner       ┆ venue        │
│ ---      ┆ ---          ┆ ---          ┆ ---          ┆ ion        ┆ ---          ┆ ---          │
│ i64      ┆ str          ┆ str          ┆ str          ┆ ---        ┆ str          ┆ str          │
│          ┆              ┆              ┆              ┆ str        ┆              ┆              │
╞══════════╪══════════════╪══════════════╪══════════════╪════════════╪══════════════╪══════════════╡
│ 1        ┆ Sunrisers    ┆ Royal        ┆ Royal        ┆ field      ┆ Sunrisers    ┆ Rajiv Gandhi │
│          ┆ Hyderabad    ┆ Challengers  ┆ Challengers  ┆            ┆ Hyderabad    ┆ Internationa │
│          ┆              ┆ Bangalore    ┆ Bangalore    ┆            ┆              ┆ l Stadi…     │
│ 2        ┆ Mumbai       ┆ Rising Pune  ┆ Rising Pune  ┆ field      ┆ Rising Pune  ┆ Maharashtra  │
│          ┆ Indians      ┆ Supergiant   ┆ Supergiant   ┆            ┆ Supergiant   ┆ Cricket      │
│          ┆              ┆              ┆              ┆            ┆              ┆ Association  │
│          ┆              ┆              ┆              ┆            ┆              ┆ …            │
│ 3        ┆ Gujarat      ┆ Kolkata      ┆ Kolkata      ┆ field      ┆ Kolkata      ┆ Saurashtra   │
│          ┆ Lions        ┆ Knight       ┆ Knight       ┆            ┆ Knight       ┆ Cricket      │
│          ┆              ┆ Riders       ┆ Riders       ┆            ┆ Riders       ┆ Association  │
│          ┆              ┆              ┆              ┆            ┆              ┆ S…           │
│ 4        ┆ Rising Pune  ┆ Kings XI     ┆ Kings XI     ┆ field      ┆ Kings XI     ┆ Holkar       │
│          ┆ Supergiant   ┆ Punjab       ┆ Punjab       ┆            ┆ Punjab       ┆ Cricket      │
│          ┆              ┆              ┆              ┆            ┆              ┆ Stadium      │
│ …        ┆ …            ┆ …            ┆ …            ┆ …          ┆ …            ┆ …            │
│ 11412    ┆ Chennai      ┆ Mumbai       ┆ Chennai      ┆ bat        ┆ Mumbai       ┆ M. A.        │
│          ┆ Super Kings  ┆ Indians      ┆ Super Kings  ┆            ┆ Indians      ┆ Chidambaram  │
│          ┆              ┆              ┆              ┆            ┆              ┆ Stadium      │
│ 11413    ┆ Sunrisers    ┆ Delhi        ┆ Delhi        ┆ field      ┆ Delhi        ┆ ACA-VDCA     │
│          ┆ Hyderabad    ┆ Capitals     ┆ Capitals     ┆            ┆ Capitals     ┆ Stadium      │
│ 11414    ┆ Delhi        ┆ Chennai      ┆ Chennai      ┆ field      ┆ Chennai      ┆ ACA-VDCA     │
│          ┆ Capitals     ┆ Super Kings  ┆ Super Kings  ┆            ┆ Super Kings  ┆ Stadium      │
│ 11415    ┆ Mumbai       ┆ Chennai      ┆ Mumbai       ┆ bat        ┆ Mumbai       ┆ Rajiv Gandhi │
│          ┆ Indians      ┆ Super Kings  ┆ Indians      ┆            ┆ Indians      ┆ Intl.        │
│          ┆              ┆              ┆              ┆            ┆              ┆ Cricket      │
│          ┆              ┆              ┆              ┆            ┆              ┆ Stadi…       │
└──────────┴──────────────┴──────────────┴──────────────┴────────────┴──────────────┴──────────────┘

In [499]:
deliveries=pl.read_csv(r"D:\Ravikumar\Git\ravikumar\statistics\testing\ipl\deliveries.csv")
deliveries=deliveries.filter(pl.col("match_id").is_in(matches["match_id"]))
deliveries

shape: (173_164, 21)
┌──────────┬────────┬────────────┬────────────┬───┬──────────┬────────────┬────────────┬───────────┐
│ match_id ┆ inning ┆ batting_te ┆ bowling_te ┆ … ┆ total_ru ┆ player_dis ┆ dismissal_ ┆ fielder   │
│ ---      ┆ ---    ┆ am         ┆ am         ┆   ┆ ns       ┆ missed     ┆ kind       ┆ ---       │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---        ┆ str       │
│          ┆        ┆ str        ┆ str        ┆   ┆ i64      ┆ str        ┆ str        ┆           │
╞══════════╪════════╪════════════╪════════════╪═══╪══════════╪════════════╪════════════╪═══════════╡
│ 1        ┆ 1      ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ 0        ┆ null       ┆ null       ┆ null      │
│          ┆        ┆ Hyderabad  ┆ lengers    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆            ┆ Bangalore  ┆   ┆          ┆            ┆            ┆           │
│ 1        ┆ 1      ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ 0        ┆ null       ┆ null       ┆ null      │
│          ┆        ┆ Hyderabad  ┆ lengers    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆            ┆ Bangalore  ┆   ┆          ┆            ┆            ┆           │
│ 1        ┆ 1      ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ 4        ┆ null       ┆ null       ┆ null      │
│          ┆        ┆ Hyderabad  ┆ lengers    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆            ┆ Bangalore  ┆   ┆          ┆            ┆            ┆           │
│ 1        ┆ 1      ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ 0        ┆ null       ┆ null       ┆ null      │
│          ┆        ┆ Hyderabad  ┆ lengers    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆            ┆ Bangalore  ┆   ┆          ┆            ┆            ┆           │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …        ┆ …          ┆ …          ┆ …         │
│ 11415    ┆ 2      ┆ Chennai    ┆ Mumbai     ┆ … ┆ 2        ┆ null       ┆ null       ┆ null      │
│          ┆        ┆ Super      ┆ Indians    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆ Kings      ┆            ┆   ┆          ┆            ┆            ┆           │
│ 11415    ┆ 2      ┆ Chennai    ┆ Mumbai     ┆ … ┆ 1        ┆ SR Watson  ┆ run out    ┆ KH Pandya │
│          ┆        ┆ Super      ┆ Indians    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆ Kings      ┆            ┆   ┆          ┆            ┆            ┆           │
│ 11415    ┆ 2      ┆ Chennai    ┆ Mumbai     ┆ … ┆ 2        ┆ null       ┆ null       ┆ null      │
│          ┆        ┆ Super      ┆ Indians    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆ Kings      ┆            ┆   ┆          ┆            ┆            ┆           │
│ 11415    ┆ 2      ┆ Chennai    ┆ Mumbai     ┆ … ┆ 0        ┆ SN Thakur  ┆ lbw        ┆ null      │
│          ┆        ┆ Super      ┆ Indians    ┆   ┆          ┆            ┆            ┆           │
│          ┆        ┆ Kings      ┆            ┆   ┆          ┆            ┆            ┆           │
└──────────┴────────┴────────────┴────────────┴───┴──────────┴────────────┴────────────┴───────────┘

In [500]:
deliveries=deliveries.drop("ball","batsman","non_striker",	"bowler","is_super_over","dismissal_kind","fielder","wide_runs"	,"bye_runs","legbye_runs","noball_runs","penalty_runs","batsman_runs","extra_runs")
deliveries

shape: (173_164, 7)
┌──────────┬────────┬───────────────┬───────────────────┬──────┬────────────┬──────────────────┐
│ match_id ┆ inning ┆ batting_team  ┆ bowling_team      ┆ over ┆ total_runs ┆ player_dismissed │
│ ---      ┆ ---    ┆ ---           ┆ ---               ┆ ---  ┆ ---        ┆ ---              │
│ i64      ┆ i64    ┆ str           ┆ str               ┆ i64  ┆ i64        ┆ str              │
╞══════════╪════════╪═══════════════╪═══════════════════╪══════╪════════════╪══════════════════╡
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 0          ┆ null             │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 0          ┆ null             │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 4          ┆ null             │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 0          ┆ null             │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ …        ┆ …      ┆ …             ┆ …                 ┆ …    ┆ …          ┆ …                │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 2          ┆ null             │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 1          ┆ SR Watson        │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 2          ┆ null             │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 0          ┆ SN Thakur        │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
└──────────┴────────┴───────────────┴───────────────────┴──────┴────────────┴──────────────────┘

In [501]:
deliveries=deliveries.with_columns(pl.col("player_dismissed").apply(lambda value : 0 if value is None else 1))
deliveries.fill_null(0)

shape: (173_164, 7)
┌──────────┬────────┬───────────────┬───────────────────┬──────┬────────────┬──────────────────┐
│ match_id ┆ inning ┆ batting_team  ┆ bowling_team      ┆ over ┆ total_runs ┆ player_dismissed │
│ ---      ┆ ---    ┆ ---           ┆ ---               ┆ ---  ┆ ---        ┆ ---              │
│ i64      ┆ i64    ┆ str           ┆ str               ┆ i64  ┆ i64        ┆ i64              │
╞══════════╪════════╪═══════════════╪═══════════════════╪══════╪════════════╪══════════════════╡
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 0          ┆ 0                │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 0          ┆ 0                │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 4          ┆ 0                │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ 1        ┆ 1      ┆ Sunrisers     ┆ Royal Challengers ┆ 1    ┆ 0          ┆ 0                │
│          ┆        ┆ Hyderabad     ┆ Bangalore         ┆      ┆            ┆                  │
│ …        ┆ …      ┆ …             ┆ …                 ┆ …    ┆ …          ┆ …                │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 2          ┆ 0                │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 1          ┆ 1                │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 2          ┆ 0                │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
│ 11415    ┆ 2      ┆ Chennai Super ┆ Mumbai Indians    ┆ 20   ┆ 0          ┆ 1                │
│          ┆        ┆ Kings         ┆                   ┆      ┆            ┆                  │
└──────────┴────────┴───────────────┴───────────────────┴──────┴────────────┴──────────────────┘

In [502]:
group_data=deliveries.groupby(pl.col("match_id"),pl.col("inning"),pl.col("over")).agg((pl.col("total_runs").sum()),(pl.col("player_dismissed").sum())).fill_null(0)#.select(deliveries["match_id"],deliveries["inning"],deliveries["batting_team"],deliveries["bowling_team"],deliveries["over"],deliveries["total_runs"],deliveries["player_dismissed"])

In [503]:
group_data.filter((pl.col("match_id")==1) & (pl.col("inning")==2)).sort(pl.col("over"))

shape: (20, 5)
┌──────────┬────────┬──────┬────────────┬──────────────────┐
│ match_id ┆ inning ┆ over ┆ total_runs ┆ player_dismissed │
│ ---      ┆ ---    ┆ ---  ┆ ---        ┆ ---              │
│ i64      ┆ i64    ┆ i64  ┆ i64        ┆ i64              │
╞══════════╪════════╪══════╪════════════╪══════════════════╡
│ 1        ┆ 2      ┆ 1    ┆ 11         ┆ 0                │
│ 1        ┆ 2      ┆ 2    ┆ 1          ┆ 0                │
│ 1        ┆ 2      ┆ 3    ┆ 16         ┆ 0                │
│ 1        ┆ 2      ┆ 4    ┆ 15         ┆ 0                │
│ …        ┆ …      ┆ …    ┆ …          ┆ …                │
│ 1        ┆ 2      ┆ 17   ┆ 3          ┆ 1                │
│ 1        ┆ 2      ┆ 18   ┆ 2          ┆ 2                │
│ 1        ┆ 2      ┆ 19   ┆ 9          ┆ 1                │
│ 1        ┆ 2      ┆ 20   ┆ 7          ┆ 1                │
└──────────┴────────┴──────┴────────────┴──────────────────┘

In [504]:
powerplay_score_data=group_data.filter(pl.col("over")<=6).groupby(["match_id", "inning"]).agg(pl.col("total_runs").sum().alias("powerplay_runs"),pl.col("player_dismissed").sum().alias("powerplay_wickets")).sort("match_id")
powerplay_score_data

shape: (1_448, 4)
┌──────────┬────────┬────────────────┬───────────────────┐
│ match_id ┆ inning ┆ powerplay_runs ┆ powerplay_wickets │
│ ---      ┆ ---    ┆ ---            ┆ ---               │
│ i64      ┆ i64    ┆ i64            ┆ i64               │
╞══════════╪════════╪════════════════╪═══════════════════╡
│ 1        ┆ 1      ┆ 59             ┆ 1                 │
│ 1        ┆ 2      ┆ 54             ┆ 1                 │
│ 2        ┆ 1      ┆ 61             ┆ 1                 │
│ 2        ┆ 2      ┆ 59             ┆ 1                 │
│ …        ┆ …      ┆ …              ┆ …                 │
│ 11414    ┆ 2      ┆ 42             ┆ 0                 │
│ 11414    ┆ 1      ┆ 42             ┆ 2                 │
│ 11415    ┆ 2      ┆ 54             ┆ 1                 │
│ 11415    ┆ 1      ┆ 46             ┆ 2                 │
└──────────┴────────┴────────────────┴───────────────────┘

In [505]:
final_score_data=group_data.groupby(["match_id", "inning"]).agg(pl.col("total_runs").sum().alias("final_runs"),pl.col("player_dismissed").sum().alias("final_wickets")).sort("match_id")
final_score_data

shape: (1_448, 4)
┌──────────┬────────┬────────────┬───────────────┐
│ match_id ┆ inning ┆ final_runs ┆ final_wickets │
│ ---      ┆ ---    ┆ ---        ┆ ---           │
│ i64      ┆ i64    ┆ i64        ┆ i64           │
╞══════════╪════════╪════════════╪═══════════════╡
│ 1        ┆ 1      ┆ 207        ┆ 4             │
│ 1        ┆ 2      ┆ 172        ┆ 10            │
│ 2        ┆ 1      ┆ 184        ┆ 8             │
│ 2        ┆ 2      ┆ 187        ┆ 3             │
│ …        ┆ …      ┆ …          ┆ …             │
│ 11414    ┆ 2      ┆ 162        ┆ 4             │
│ 11414    ┆ 1      ┆ 155        ┆ 9             │
│ 11415    ┆ 2      ┆ 157        ┆ 7             │
│ 11415    ┆ 1      ┆ 152        ┆ 8             │
└──────────┴────────┴────────────┴───────────────┘

In [506]:
score_data=powerplay_score_data.join(final_score_data,on=["match_id", "inning"],how="inner")
score_data

shape: (1_448, 6)
┌──────────┬────────┬────────────────┬───────────────────┬────────────┬───────────────┐
│ match_id ┆ inning ┆ powerplay_runs ┆ powerplay_wickets ┆ final_runs ┆ final_wickets │
│ ---      ┆ ---    ┆ ---            ┆ ---               ┆ ---        ┆ ---           │
│ i64      ┆ i64    ┆ i64            ┆ i64               ┆ i64        ┆ i64           │
╞══════════╪════════╪════════════════╪═══════════════════╪════════════╪═══════════════╡
│ 1        ┆ 1      ┆ 59             ┆ 1                 ┆ 207        ┆ 4             │
│ 1        ┆ 2      ┆ 54             ┆ 1                 ┆ 172        ┆ 10            │
│ 2        ┆ 1      ┆ 61             ┆ 1                 ┆ 184        ┆ 8             │
│ 2        ┆ 2      ┆ 59             ┆ 1                 ┆ 187        ┆ 3             │
│ …        ┆ …      ┆ …              ┆ …                 ┆ …          ┆ …             │
│ 11414    ┆ 2      ┆ 42             ┆ 0                 ┆ 162        ┆ 4             │
│ 11414    ┆ 1      ┆ 42             ┆ 2                 ┆ 155        ┆ 9             │
│ 11415    ┆ 2      ┆ 54             ┆ 1                 ┆ 157        ┆ 7             │
│ 11415    ┆ 1      ┆ 46             ┆ 2                 ┆ 152        ┆ 8             │
└──────────┴────────┴────────────────┴───────────────────┴────────────┴───────────────┘

In [507]:
deliveries=deliveries.drop("over","total_runs","player_dismissed")
deliveries=deliveries.with_columns(deliveries["match_id"],deliveries["inning"],deliveries["batting_team"],deliveries["bowling_team"]).groupby("match_id", "inning","batting_team","bowling_team").agg().sort("match_id", "inning")
deliveries

shape: (1_448, 4)
┌──────────┬────────┬─────────────────────────────┬─────────────────────────────┐
│ match_id ┆ inning ┆ batting_team                ┆ bowling_team                │
│ ---      ┆ ---    ┆ ---                         ┆ ---                         │
│ i64      ┆ i64    ┆ str                         ┆ str                         │
╞══════════╪════════╪═════════════════════════════╪═════════════════════════════╡
│ 1        ┆ 1      ┆ Sunrisers Hyderabad         ┆ Royal Challengers Bangalore │
│ 1        ┆ 2      ┆ Royal Challengers Bangalore ┆ Sunrisers Hyderabad         │
│ 2        ┆ 1      ┆ Mumbai Indians              ┆ Rising Pune Supergiant      │
│ 2        ┆ 2      ┆ Rising Pune Supergiant      ┆ Mumbai Indians              │
│ …        ┆ …      ┆ …                           ┆ …                           │
│ 11414    ┆ 1      ┆ Delhi Capitals              ┆ Chennai Super Kings         │
│ 11414    ┆ 2      ┆ Chennai Super Kings         ┆ Delhi Capitals              │
│ 11415    ┆ 1      ┆ Mumbai Indians              ┆ Chennai Super Kings         │
│ 11415    ┆ 2      ┆ Chennai Super Kings         ┆ Mumbai Indians              │
└──────────┴────────┴─────────────────────────────┴─────────────────────────────┘

In [508]:
deliveries=deliveries.join(score_data,on=["match_id","inning"]).join(matches,on=["match_id"]).drop("final_wickets","winner","venue")
deliveries

shape: (1_448, 11)
┌──────────┬────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ match_id ┆ inning ┆ batting_te ┆ bowling_te ┆ … ┆ team1     ┆ team2     ┆ toss_winn ┆ toss_decis │
│ ---      ┆ ---    ┆ am         ┆ am         ┆   ┆ ---       ┆ ---       ┆ er        ┆ ion        │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---        │
│          ┆        ┆ str        ┆ str        ┆   ┆           ┆           ┆ str       ┆ str        │
╞══════════╪════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 1        ┆ 1      ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ Sunrisers ┆ Royal Cha ┆ Royal Cha ┆ field      │
│          ┆        ┆ Hyderabad  ┆ lengers    ┆   ┆ Hyderabad ┆ llengers  ┆ llengers  ┆            │
│          ┆        ┆            ┆ Bangalore  ┆   ┆           ┆ Bangalore ┆ Bangalore ┆            │
│ 1        ┆ 2      ┆ Royal Chal ┆ Sunrisers  ┆ … ┆ Sunrisers ┆ Royal Cha ┆ Royal Cha ┆ field      │
│          ┆        ┆ lengers    ┆ Hyderabad  ┆   ┆ Hyderabad ┆ llengers  ┆ llengers  ┆            │
│          ┆        ┆ Bangalore  ┆            ┆   ┆           ┆ Bangalore ┆ Bangalore ┆            │
│ 2        ┆ 1      ┆ Mumbai     ┆ Rising     ┆ … ┆ Mumbai    ┆ Rising    ┆ Rising    ┆ field      │
│          ┆        ┆ Indians    ┆ Pune       ┆   ┆ Indians   ┆ Pune Supe ┆ Pune Supe ┆            │
│          ┆        ┆            ┆ Supergiant ┆   ┆           ┆ rgiant    ┆ rgiant    ┆            │
│ 2        ┆ 2      ┆ Rising     ┆ Mumbai     ┆ … ┆ Mumbai    ┆ Rising    ┆ Rising    ┆ field      │
│          ┆        ┆ Pune       ┆ Indians    ┆   ┆ Indians   ┆ Pune Supe ┆ Pune Supe ┆            │
│          ┆        ┆ Supergiant ┆            ┆   ┆           ┆ rgiant    ┆ rgiant    ┆            │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …          │
│ 11414    ┆ 2      ┆ Chennai    ┆ Delhi      ┆ … ┆ Delhi     ┆ Chennai   ┆ Chennai   ┆ field      │
│          ┆        ┆ Super      ┆ Capitals   ┆   ┆ Capitals  ┆ Super     ┆ Super     ┆            │
│          ┆        ┆ Kings      ┆            ┆   ┆           ┆ Kings     ┆ Kings     ┆            │
│ 11414    ┆ 1      ┆ Delhi      ┆ Chennai    ┆ … ┆ Delhi     ┆ Chennai   ┆ Chennai   ┆ field      │
│          ┆        ┆ Capitals   ┆ Super      ┆   ┆ Capitals  ┆ Super     ┆ Super     ┆            │
│          ┆        ┆            ┆ Kings      ┆   ┆           ┆ Kings     ┆ Kings     ┆            │
│ 11415    ┆ 2      ┆ Chennai    ┆ Mumbai     ┆ … ┆ Mumbai    ┆ Chennai   ┆ Mumbai    ┆ bat        │
│          ┆        ┆ Super      ┆ Indians    ┆   ┆ Indians   ┆ Super     ┆ Indians   ┆            │
│          ┆        ┆ Kings      ┆            ┆   ┆           ┆ Kings     ┆           ┆            │
│ 11415    ┆ 1      ┆ Mumbai     ┆ Chennai    ┆ … ┆ Mumbai    ┆ Chennai   ┆ Mumbai    ┆ bat        │
│          ┆        ┆ Indians    ┆ Super      ┆   ┆ Indians   ┆ Super     ┆ Indians   ┆            │
│          ┆        ┆            ┆ Kings      ┆   ┆           ┆ Kings     ┆           ┆            │
└──────────┴────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴────────────┘

In [509]:
import pyarrow

In [510]:
deliveries["batting_team"].unique().to_arrow()

<pyarrow.lib.LargeStringArray object at 0x00000271167EF700>
[
  "Mumbai Indians",
  "Rising Pune Supergiants",
  "Royal Challengers Bangalore",
  "Kochi Tuskers Kerala",
  "Chennai Super Kings",
  "Kings XI Punjab",
  "Rising Pune Supergiant",
  "Gujarat Lions",
  "Delhi Daredevils",
  "Deccan Chargers",
  "Rajasthan Royals",
  "Sunrisers Hyderabad",
  "Delhi Capitals",
  "Pune Warriors",
  "Kolkata Knight Riders"
]

In [511]:
deliveries=deliveries.filter(pl.col("team1")!="Kochi Tuskers Kerala").filter(pl.col("team1")!="Deccan Chargers").filter(pl.col("team2")!="Kochi Tuskers Kerala").filter(pl.col("team2")!="Deccan Chargers")
deliveries

shape: (1_274, 11)
┌──────────┬────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ match_id ┆ inning ┆ batting_te ┆ bowling_te ┆ … ┆ team1     ┆ team2     ┆ toss_winn ┆ toss_decis │
│ ---      ┆ ---    ┆ am         ┆ am         ┆   ┆ ---       ┆ ---       ┆ er        ┆ ion        │
│ i64      ┆ i64    ┆ ---        ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---        │
│          ┆        ┆ str        ┆ str        ┆   ┆           ┆           ┆ str       ┆ str        │
╞══════════╪════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 1        ┆ 1      ┆ Sunrisers  ┆ Royal Chal ┆ … ┆ Sunrisers ┆ Royal Cha ┆ Royal Cha ┆ field      │
│          ┆        ┆ Hyderabad  ┆ lengers    ┆   ┆ Hyderabad ┆ llengers  ┆ llengers  ┆            │
│          ┆        ┆            ┆ Bangalore  ┆   ┆           ┆ Bangalore ┆ Bangalore ┆            │
│ 1        ┆ 2      ┆ Royal Chal ┆ Sunrisers  ┆ … ┆ Sunrisers ┆ Royal Cha ┆ Royal Cha ┆ field      │
│          ┆        ┆ lengers    ┆ Hyderabad  ┆   ┆ Hyderabad ┆ llengers  ┆ llengers  ┆            │
│          ┆        ┆ Bangalore  ┆            ┆   ┆           ┆ Bangalore ┆ Bangalore ┆            │
│ 2        ┆ 1      ┆ Mumbai     ┆ Rising     ┆ … ┆ Mumbai    ┆ Rising    ┆ Rising    ┆ field      │
│          ┆        ┆ Indians    ┆ Pune       ┆   ┆ Indians   ┆ Pune Supe ┆ Pune Supe ┆            │
│          ┆        ┆            ┆ Supergiant ┆   ┆           ┆ rgiant    ┆ rgiant    ┆            │
│ 2        ┆ 2      ┆ Rising     ┆ Mumbai     ┆ … ┆ Mumbai    ┆ Rising    ┆ Rising    ┆ field      │
│          ┆        ┆ Pune       ┆ Indians    ┆   ┆ Indians   ┆ Pune Supe ┆ Pune Supe ┆            │
│          ┆        ┆ Supergiant ┆            ┆   ┆           ┆ rgiant    ┆ rgiant    ┆            │
│ …        ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …          │
│ 11414    ┆ 2      ┆ Chennai    ┆ Delhi      ┆ … ┆ Delhi     ┆ Chennai   ┆ Chennai   ┆ field      │
│          ┆        ┆ Super      ┆ Capitals   ┆   ┆ Capitals  ┆ Super     ┆ Super     ┆            │
│          ┆        ┆ Kings      ┆            ┆   ┆           ┆ Kings     ┆ Kings     ┆            │
│ 11414    ┆ 1      ┆ Delhi      ┆ Chennai    ┆ … ┆ Delhi     ┆ Chennai   ┆ Chennai   ┆ field      │
│          ┆        ┆ Capitals   ┆ Super      ┆   ┆ Capitals  ┆ Super     ┆ Super     ┆            │
│          ┆        ┆            ┆ Kings      ┆   ┆           ┆ Kings     ┆ Kings     ┆            │
│ 11415    ┆ 2      ┆ Chennai    ┆ Mumbai     ┆ … ┆ Mumbai    ┆ Chennai   ┆ Mumbai    ┆ bat        │
│          ┆        ┆ Super      ┆ Indians    ┆   ┆ Indians   ┆ Super     ┆ Indians   ┆            │
│          ┆        ┆ Kings      ┆            ┆   ┆           ┆ Kings     ┆           ┆            │
│ 11415    ┆ 1      ┆ Mumbai     ┆ Chennai    ┆ … ┆ Mumbai    ┆ Chennai   ┆ Mumbai    ┆ bat        │
│          ┆        ┆ Indians    ┆ Super      ┆   ┆ Indians   ┆ Super     ┆ Indians   ┆            │
│          ┆        ┆            ┆ Kings      ┆   ┆           ┆ Kings     ┆           ┆            │
└──────────┴────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴────────────┘

In [512]:
deliveries=deliveries.with_columns(pl.col("batting_team").str.replace("Rising Pune Supergiant","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("bowling_team").str.replace("Rising Pune Supergiant","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("team1").str.replace("Rising Pune Supergiant","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("team2").str.replace("Rising Pune Supergiant","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("toss_winner").str.replace("Rising Pune Supergiant","Pune Warriors"))

deliveries=deliveries.with_columns(pl.col("batting_team").str.replace("Rising Pune Supergiants","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("bowling_team").str.replace("Rising Pune Supergiants","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("team1").str.replace("Rising Pune Supergiants","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("team2").str.replace("Rising Pune Supergiants","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("toss_winner").str.replace("Rising Pune Supergiants","Pune Warriors"))

deliveries=deliveries.with_columns(pl.col("batting_team").str.replace("Pune Warriorss","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("bowling_team").str.replace("Pune Warriorss","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("team1").str.replace("Pune Warriorss","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("team2").str.replace("Pune Warriorss","Pune Warriors"))
deliveries=deliveries.with_columns(pl.col("toss_winner").str.replace("Pune Warriorss","Pune Warriors"))

deliveries=deliveries.with_columns(pl.col("batting_team").str.replace("Delhi Daredevils","Delhi Capitals"))
deliveries=deliveries.with_columns(pl.col("bowling_team").str.replace("Delhi Daredevils","Delhi Capitals"))
deliveries=deliveries.with_columns(pl.col("team1").str.replace("Delhi Daredevils","Delhi Capitals"))
deliveries=deliveries.with_columns(pl.col("team2").str.replace("Delhi Daredevils","Delhi Capitals"))
deliveries=deliveries.with_columns(pl.col("toss_winner").str.replace("Delhi Daredevils","Delhi Capitals"))


deliveries=deliveries.with_columns(pl.col("toss_decision").str.replace("field",1)).with_columns(pl.col("toss_decision").str.replace("bat",0))

In [513]:
deliveries=deliveries.with_columns(deliveries["toss_decision"].cast(pl.Int64())).drop("match_id")

In [514]:
deliveries=deliveries.with_columns((pl.col("powerplay_runs")/6).alias("powerplay_run_rate"))
deliveries

shape: (1_274, 11)
┌────────┬────────────┬────────────┬────────────┬───┬────────┬───────────┬────────────┬────────────┐
│ inning ┆ batting_te ┆ bowling_te ┆ powerplay_ ┆ … ┆ team2  ┆ toss_winn ┆ toss_decis ┆ powerplay_ │
│ ---    ┆ am         ┆ am         ┆ runs       ┆   ┆ ---    ┆ er        ┆ ion        ┆ run_rate   │
│ i64    ┆ ---        ┆ ---        ┆ ---        ┆   ┆ str    ┆ ---       ┆ ---        ┆ ---        │
│        ┆ str        ┆ str        ┆ i64        ┆   ┆        ┆ str       ┆ i64        ┆ f64        │
╞════════╪════════════╪════════════╪════════════╪═══╪════════╪═══════════╪════════════╪════════════╡
│ 1      ┆ Sunrisers  ┆ Royal Chal ┆ 59         ┆ … ┆ Royal  ┆ Royal Cha ┆ 1          ┆ 9.833333   │
│        ┆ Hyderabad  ┆ lengers    ┆            ┆   ┆ Challe ┆ llengers  ┆            ┆            │
│        ┆            ┆ Bangalore  ┆            ┆   ┆ ngers  ┆ Bangalore ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ Bangal ┆           ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ ore    ┆           ┆            ┆            │
│ 2      ┆ Royal Chal ┆ Sunrisers  ┆ 54         ┆ … ┆ Royal  ┆ Royal Cha ┆ 1          ┆ 9.0        │
│        ┆ lengers    ┆ Hyderabad  ┆            ┆   ┆ Challe ┆ llengers  ┆            ┆            │
│        ┆ Bangalore  ┆            ┆            ┆   ┆ ngers  ┆ Bangalore ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ Bangal ┆           ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ ore    ┆           ┆            ┆            │
│ 1      ┆ Mumbai     ┆ Pune       ┆ 61         ┆ … ┆ Pune   ┆ Pune      ┆ 1          ┆ 10.166667  │
│        ┆ Indians    ┆ Warriors   ┆            ┆   ┆ Warrio ┆ Warriors  ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ rs     ┆           ┆            ┆            │
│ 2      ┆ Pune       ┆ Mumbai     ┆ 59         ┆ … ┆ Pune   ┆ Pune      ┆ 1          ┆ 9.833333   │
│        ┆ Warriors   ┆ Indians    ┆            ┆   ┆ Warrio ┆ Warriors  ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ rs     ┆           ┆            ┆            │
│ …      ┆ …          ┆ …          ┆ …          ┆ … ┆ …      ┆ …         ┆ …          ┆ …          │
│ 2      ┆ Chennai    ┆ Delhi      ┆ 42         ┆ … ┆ Chenna ┆ Chennai   ┆ 1          ┆ 7.0        │
│        ┆ Super      ┆ Capitals   ┆            ┆   ┆ i      ┆ Super     ┆            ┆            │
│        ┆ Kings      ┆            ┆            ┆   ┆ Super  ┆ Kings     ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ Kings  ┆           ┆            ┆            │
│ 1      ┆ Delhi      ┆ Chennai    ┆ 42         ┆ … ┆ Chenna ┆ Chennai   ┆ 1          ┆ 7.0        │
│        ┆ Capitals   ┆ Super      ┆            ┆   ┆ i      ┆ Super     ┆            ┆            │
│        ┆            ┆ Kings      ┆            ┆   ┆ Super  ┆ Kings     ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ Kings  ┆           ┆            ┆            │
│ 2      ┆ Chennai    ┆ Mumbai     ┆ 54         ┆ … ┆ Chenna ┆ Mumbai    ┆ 0          ┆ 9.0        │
│        ┆ Super      ┆ Indians    ┆            ┆   ┆ i      ┆ Indians   ┆            ┆            │
│        ┆ Kings      ┆            ┆            ┆   ┆ Super  ┆           ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ Kings  ┆           ┆            ┆            │
│ 1      ┆ Mumbai     ┆ Chennai    ┆ 46         ┆ … ┆ Chenna ┆ Mumbai    ┆ 0          ┆ 7.666667   │
│        ┆ Indians    ┆ Super      ┆            ┆   ┆ i      ┆ Indians   ┆            ┆            │
│        ┆            ┆ Kings      ┆            ┆   ┆ Super  ┆           ┆            ┆            │
│        ┆            ┆            ┆            ┆   ┆ Kings  ┆           ┆            ┆            │
└────────┴────────────┴────────────┴────────────┴───┴────────┴───────────┴────────────┴────────────┘

In [515]:
deliveries=deliveries.with_columns(pl.concat_str([pl.col("batting_team")+" batting team"]) )
deliveries=deliveries.with_columns(pl.concat_str([pl.col("bowling_team")+" bowling team"]))

In [516]:
import pandas as pd

In [517]:
deliveries=deliveries.to_pandas()

In [491]:
deliveries

,inning,batting_team,bowling_team,powerplay_runs,powerplay_wickets,final_runs,team1,team2,toss_winner,toss_decision,powerplay_run_rate
0,1,Sunrisers Hyderabad batting team,Royal Challengers Bangalore bowling team,59,1,207,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,1,9.833333
1,2,Royal Challengers Bangalore batting team,Sunrisers Hyderabad bowling team,54,1,172,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,1,9.000000
2,1,Mumbai Indians batting team,Pune Warriors bowling team,61,1,184,Mumbai Indians,Pune Warriors,Pune Warriors,1,10.166667
3,2,Pune Warriors batting team,Mumbai Indians bowling team,59,1,187,Mumbai Indians,Pune Warriors,Pune Warriors,1,9.833333
4,2,Kolkata Knight Riders batting team,Gujarat Lions bowling team,73,0,184,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,1,12.166667
...,...,...,...,...,...,...,...,...,...,...,...
1269,1,Sunrisers Hyderabad batting team,Delhi Capitals bowling team,54,1,171,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,1,9.000000
1270,2,Chennai Super Kings batting team,Delhi Capitals bowling team,42,0,162,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,1,7.000000
1271,1,Delhi Capitals batting team,Chennai Super Kings bowling team,42,2,155,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,1,7.000000
1272,2,Chennai Super Kings batting team,Mumbai Indians bowling team,54,1,157,Mumbai Indians,Chennai Super Kings,Mumbai Indians,0,9.000000
1273,1,Mumbai Indians batting team,Chennai Super Kings bowling team,46,2,152,Mumbai Indians,Chennai Super Kings,Mumbai Indians,0,7.666667

In [518]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
ohe=OneHotEncoder()

In [519]:
deliveries["team1"]=le.fit_transform(deliveries[["team1"]])
deliveries["team2"]=le.fit_transform(deliveries[["team2"]])
deliveries["toss_winner"]=le.fit_transform(deliveries[["toss_winner"]])
deliveries

,inning,batting_team,bowling_team,powerplay_runs,powerplay_wickets,final_runs,team1,team2,toss_winner,toss_decision,powerplay_run_rate
0,1,Sunrisers Hyderabad batting team,Royal Challengers Bangalore bowling team,59,1,207,9,8,8,1,9.833333
1,2,Royal Challengers Bangalore batting team,Sunrisers Hyderabad bowling team,54,1,172,9,8,8,1,9.000000
2,1,Mumbai Indians batting team,Pune Warriors bowling team,61,1,184,5,6,6,1,10.166667
3,2,Pune Warriors batting team,Mumbai Indians bowling team,59,1,187,5,6,6,1,9.833333
4,2,Kolkata Knight Riders batting team,Gujarat Lions bowling team,73,0,184,2,4,4,1,12.166667
...,...,...,...,...,...,...,...,...,...,...,...
1269,1,Sunrisers Hyderabad batting team,Delhi Capitals bowling team,54,1,171,9,1,1,1,9.000000
1270,2,Chennai Super Kings batting team,Delhi Capitals bowling team,42,0,162,1,0,0,1,7.000000
1271,1,Delhi Capitals batting team,Chennai Super Kings bowling team,42,2,155,1,0,0,1,7.000000
1272,2,Chennai Super Kings batting team,Mumbai Indians bowling team,54,1,157,5,0,5,0,9.000000
1273,1,Mumbai Indians batting team,Chennai Super Kings bowling team,46,2,152,5,0,5,0,7.666667

In [520]:
map=dict(zip(range(len(le.classes_)),le.classes_))
map

{0: 'Chennai Super Kings',
 1: 'Delhi Capitals',
 2: 'Gujarat Lions',
 3: 'Kings XI Punjab',
 4: 'Kolkata Knight Riders',
 5: 'Mumbai Indians',
 6: 'Pune Warriors',
 7: 'Rajasthan Royals',
 8: 'Royal Challengers Bangalore',
 9: 'Sunrisers Hyderabad'}

In [521]:
deliveries

,inning,batting_team,bowling_team,powerplay_runs,powerplay_wickets,final_runs,team1,team2,toss_winner,toss_decision,powerplay_run_rate
0,1,Sunrisers Hyderabad batting team,Royal Challengers Bangalore bowling team,59,1,207,9,8,8,1,9.833333
1,2,Royal Challengers Bangalore batting team,Sunrisers Hyderabad bowling team,54,1,172,9,8,8,1,9.000000
2,1,Mumbai Indians batting team,Pune Warriors bowling team,61,1,184,5,6,6,1,10.166667
3,2,Pune Warriors batting team,Mumbai Indians bowling team,59,1,187,5,6,6,1,9.833333
4,2,Kolkata Knight Riders batting team,Gujarat Lions bowling team,73,0,184,2,4,4,1,12.166667
...,...,...,...,...,...,...,...,...,...,...,...
1269,1,Sunrisers Hyderabad batting team,Delhi Capitals bowling team,54,1,171,9,1,1,1,9.000000
1270,2,Chennai Super Kings batting team,Delhi Capitals bowling team,42,0,162,1,0,0,1,7.000000
1271,1,Delhi Capitals batting team,Chennai Super Kings bowling team,42,2,155,1,0,0,1,7.000000
1272,2,Chennai Super Kings batting team,Mumbai Indians bowling team,54,1,157,5,0,5,0,9.000000
1273,1,Mumbai Indians batting team,Chennai Super Kings bowling team,46,2,152,5,0,5,0,7.666667

In [522]:
cat_array=ohe.fit_transform(deliveries[["batting_team","bowling_team"]]).toarray()
cat_array

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [523]:
cat_var=ohe.categories_
cat_var

[array(['Chennai Super Kings batting team', 'Delhi Capitals batting team',
        'Gujarat Lions batting team', 'Kings XI Punjab batting team',
        'Kolkata Knight Riders batting team',
        'Mumbai Indians batting team', 'Pune Warriors batting team',
        'Rajasthan Royals batting team',
        'Royal Challengers Bangalore batting team',
        'Sunrisers Hyderabad batting team'], dtype=object),
 array(['Chennai Super Kings bowling team', 'Delhi Capitals bowling team',
        'Gujarat Lions bowling team', 'Kings XI Punjab bowling team',
        'Kolkata Knight Riders bowling team',
        'Mumbai Indians bowling team', 'Pune Warriors bowling team',
        'Rajasthan Royals bowling team',
        'Royal Challengers Bangalore bowling team',
        'Sunrisers Hyderabad bowling team'], dtype=object)]

In [524]:
combined_cat_var=np.array(cat_var).ravel()
combined_cat_var

array(['Chennai Super Kings batting team', 'Delhi Capitals batting team',
       'Gujarat Lions batting team', 'Kings XI Punjab batting team',
       'Kolkata Knight Riders batting team',
       'Mumbai Indians batting team', 'Pune Warriors batting team',
       'Rajasthan Royals batting team',
       'Royal Challengers Bangalore batting team',
       'Sunrisers Hyderabad batting team',
       'Chennai Super Kings bowling team', 'Delhi Capitals bowling team',
       'Gujarat Lions bowling team', 'Kings XI Punjab bowling team',
       'Kolkata Knight Riders bowling team',
       'Mumbai Indians bowling team', 'Pune Warriors bowling team',
       'Rajasthan Royals bowling team',
       'Royal Challengers Bangalore bowling team',
       'Sunrisers Hyderabad bowling team'], dtype=object)

In [525]:
encode=pd.DataFrame(cat_array, columns=combined_cat_var)
encode

,Chennai Super Kings batting team,Delhi Capitals batting team,Gujarat Lions batting team,Kings XI Punjab batting team,Kolkata Knight Riders batting team,Mumbai Indians batting team,Pune Warriors batting team,Rajasthan Royals batting team,Royal Challengers Bangalore batting team,Sunrisers Hyderabad batting team,Chennai Super Kings bowling team,Delhi Capitals bowling team,Gujarat Lions bowling team,Kings XI Punjab bowling team,Kolkata Knight Riders bowling team,Mumbai Indians bowling team,Pune Warriors bowling team,Rajasthan Royals bowling team,Royal Challengers Bangalore bowling team,Sunrisers Hyderabad bowling team
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1272,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1273,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [526]:
data=pd.concat([deliveries,encode],axis=1)
unordered_data=data.drop(["batting_team","bowling_team"],axis=1)
unordered_data

,inning,powerplay_runs,powerplay_wickets,final_runs,team1,team2,toss_winner,toss_decision,powerplay_run_rate,Chennai Super Kings batting team,...,Chennai Super Kings bowling team,Delhi Capitals bowling team,Gujarat Lions bowling team,Kings XI Punjab bowling team,Kolkata Knight Riders bowling team,Mumbai Indians bowling team,Pune Warriors bowling team,Rajasthan Royals bowling team,Royal Challengers Bangalore bowling team,Sunrisers Hyderabad bowling team
0,1,59,1,207,9,8,8,1,9.833333,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,54,1,172,9,8,8,1,9.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1,61,1,184,5,6,6,1,10.166667,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,2,59,1,187,5,6,6,1,9.833333,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,2,73,0,184,2,4,4,1,12.166667,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1,54,1,171,9,1,1,1,9.000000,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1270,2,42,0,162,1,0,0,1,7.000000,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1271,1,42,2,155,1,0,0,1,7.000000,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1272,2,54,1,157,5,0,5,0,9.000000,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1273,1,46,2,152,5,0,5,0,7.666667,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [527]:
unordered_data.columns.tolist()

['inning',
 'powerplay_runs',
 'powerplay_wickets',
 'final_runs',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'powerplay_run_rate',
 'Chennai Super Kings batting team',
 'Delhi Capitals batting team',
 'Gujarat Lions batting team',
 'Kings XI Punjab batting team',
 'Kolkata Knight Riders batting team',
 'Mumbai Indians batting team',
 'Pune Warriors batting team',
 'Rajasthan Royals batting team',
 'Royal Challengers Bangalore batting team',
 'Sunrisers Hyderabad batting team',
 'Chennai Super Kings bowling team',
 'Delhi Capitals bowling team',
 'Gujarat Lions bowling team',
 'Kings XI Punjab bowling team',
 'Kolkata Knight Riders bowling team',
 'Mumbai Indians bowling team',
 'Pune Warriors bowling team',
 'Rajasthan Royals bowling team',
 'Royal Challengers Bangalore bowling team',
 'Sunrisers Hyderabad bowling team']

In [528]:
order_list=['inning','Chennai Super Kings batting team','Delhi Capitals batting team','Gujarat Lions batting team','Kings XI Punjab batting team','Kolkata Knight Riders batting team','Mumbai Indians batting team',
 'Pune Warriors batting team','Rajasthan Royals batting team','Royal Challengers Bangalore batting team','Sunrisers Hyderabad batting team','Chennai Super Kings bowling team','Delhi Capitals bowling team',
 'Gujarat Lions bowling team','Kings XI Punjab bowling team','Kolkata Knight Riders bowling team','Mumbai Indians bowling team','Pune Warriors bowling team','Rajasthan Royals bowling team','Royal Challengers Bangalore bowling team',
 'Sunrisers Hyderabad bowling team','team1','team2','toss_winner','toss_decision','powerplay_runs','powerplay_wickets','powerplay_run_rate','final_runs']

In [529]:
final_data=unordered_data.reindex(order_list,axis=1)
final_data

,inning,Chennai Super Kings batting team,Delhi Capitals batting team,Gujarat Lions batting team,Kings XI Punjab batting team,Kolkata Knight Riders batting team,Mumbai Indians batting team,Pune Warriors batting team,Rajasthan Royals batting team,Royal Challengers Bangalore batting team,...,Royal Challengers Bangalore bowling team,Sunrisers Hyderabad bowling team,team1,team2,toss_winner,toss_decision,powerplay_runs,powerplay_wickets,powerplay_run_rate,final_runs
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,9,8,8,1,59,1,9.833333,207
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,9,8,8,1,54,1,9.000000,172
2,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,5,6,6,1,61,1,10.166667,184
3,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,5,6,6,1,59,1,9.833333,187
4,2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2,4,4,1,73,0,12.166667,184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9,1,1,1,54,1,9.000000,171
1270,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1,0,0,1,42,0,7.000000,162
1271,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1,0,0,1,42,2,7.000000,155
1272,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5,0,5,0,54,1,9.000000,157
1273,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,5,0,5,0,46,2,7.666667,152

In [530]:
final_data.describe()

,inning,Chennai Super Kings batting team,Delhi Capitals batting team,Gujarat Lions batting team,Kings XI Punjab batting team,Kolkata Knight Riders batting team,Mumbai Indians batting team,Pune Warriors batting team,Rajasthan Royals batting team,Royal Challengers Bangalore batting team,...,Royal Challengers Bangalore bowling team,Sunrisers Hyderabad bowling team,team1,team2,toss_winner,toss_decision,powerplay_runs,powerplay_wickets,powerplay_run_rate,final_runs
count,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,...,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000,1274.000000
mean,1.500000,0.116170,0.120879,0.022763,0.123234,0.122449,0.136578,0.052590,0.101256,0.124804,...,0.124804,0.079278,4.518053,4.372057,4.320251,0.623234,46.179749,1.418367,7.696625,157.544741
std,0.500196,0.320554,0.326115,0.149205,0.328835,0.327932,0.343536,0.223302,0.301786,0.330626,...,0.330626,0.270278,2.880452,2.846925,2.847435,0.484766,12.151435,1.101313,2.025239,31.036405
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,0.000000,2.333333,49.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,3.000000,2.000000,1.000000,0.000000,38.000000,1.000000,6.333333,138.000000
50%,1.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,5.000000,4.000000,4.000000,1.000000,46.000000,1.000000,7.666667,159.000000
75%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.000000,7.000000,7.000000,1.000000,54.000000,2.000000,9.000000,179.000000
max,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,9.000000,9.000000,9.000000,1.000000,105.000000,5.000000,17.500000,263.000000

In [531]:
from pycaret.regression import *

In [546]:
s=setup(final_data,target="final_runs",train_size=0.8,use_gpu=True)

In [547]:
best=compare_models()

Processing:   0%|          | 0/77 [00:00<?, ?it/s]

In [548]:
best

BayesianRidge()

In [549]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [550]:
predict_model(best)

,inning,Chennai Super Kings batting team,Delhi Capitals batting team,Gujarat Lions batting team,Kings XI Punjab batting team,Kolkata Knight Riders batting team,Mumbai Indians batting team,Pune Warriors batting team,Rajasthan Royals batting team,Royal Challengers Bangalore batting team,...,Sunrisers Hyderabad bowling team,team1,team2,toss_winner,toss_decision,powerplay_runs,powerplay_wickets,powerplay_run_rate,final_runs,prediction_label
772,2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,3,4,4,1,55,0,9.166667,150,167.774170
26,1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,4,9,9,1,40,2,6.666667,172,153.221085
482,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,6,6,1,42,0,7.000000,164,169.352905
313,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,8,0,8,0,56,0,9.333333,162,172.670349
409,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,5,6,6,1,31,2,5.166667,139,129.834793
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,4,8,4,0,46,0,7.666667,143,157.217545
124,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0,5,5,1,52,2,8.666667,202,155.605133
565,2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,8,5,5,1,38,0,6.333333,154,156.680801
904,2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,3,4,3,0,57,1,9.500000,184,162.136780
267,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0,3,0,0,50,1,8.333333,116,174.666245

In [551]:
from joblib import load,dump

In [552]:
dump(best,"ipl_model_2.pkl")

['ipl_model_2.pkl']

In [553]:
model=load(r"D:\Ravikumar\Git\ravikumar\statistics\testing\ipl\ipl_model_2.pkl")

In [554]:
X=final_data.drop(["final_runs"],axis=1)
X

,inning,Chennai Super Kings batting team,Delhi Capitals batting team,Gujarat Lions batting team,Kings XI Punjab batting team,Kolkata Knight Riders batting team,Mumbai Indians batting team,Pune Warriors batting team,Rajasthan Royals batting team,Royal Challengers Bangalore batting team,...,Rajasthan Royals bowling team,Royal Challengers Bangalore bowling team,Sunrisers Hyderabad bowling team,team1,team2,toss_winner,toss_decision,powerplay_runs,powerplay_wickets,powerplay_run_rate
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,9,8,8,1,59,1,9.833333
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,9,8,8,1,54,1,9.000000
2,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5,6,6,1,61,1,10.166667
3,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,5,6,6,1,59,1,9.833333
4,2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2,4,4,1,73,0,12.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,9,1,1,1,54,1,9.000000
1270,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1,0,0,1,42,0,7.000000
1271,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1,0,0,1,42,2,7.000000
1272,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5,0,5,0,54,1,9.000000
1273,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5,0,5,0,46,2,7.666667

In [555]:
X.iloc[37]

inning                                       1.000000
Chennai Super Kings batting team             0.000000
Delhi Capitals batting team                  0.000000
Gujarat Lions batting team                   0.000000
Kings XI Punjab batting team                 0.000000
Kolkata Knight Riders batting team           0.000000
Mumbai Indians batting team                  0.000000
Pune Warriors batting team                   0.000000
Rajasthan Royals batting team                0.000000
Royal Challengers Bangalore batting team     0.000000
Sunrisers Hyderabad batting team             1.000000
Chennai Super Kings bowling team             0.000000
Delhi Capitals bowling team                  0.000000
Gujarat Lions bowling team                   0.000000
Kings XI Punjab bowling team                 1.000000
Kolkata Knight Riders bowling team           0.000000
Mumbai Indians bowling team                  0.000000
Pune Warriors bowling team                   0.000000
Rajasthan Royals bowling team                0.000000
Royal Challengers Bangalore bowling team     0.000000
Sunrisers Hyderabad bowling team             0.000000
team1                                        9.000000
team2                                        3.000000
toss_winner                                  3.000000
toss_decision                                1.000000
powerplay_runs                              29.000000
powerplay_wickets                            1.000000
powerplay_run_rate                           4.833333
Name: 37, dtype: float64

In [556]:
final_data.iloc[38]

inning                                        2.0
Chennai Super Kings batting team              0.0
Delhi Capitals batting team                   0.0
Gujarat Lions batting team                    1.0
Kings XI Punjab batting team                  0.0
Kolkata Knight Riders batting team            0.0
Mumbai Indians batting team                   0.0
Pune Warriors batting team                    0.0
Rajasthan Royals batting team                 0.0
Royal Challengers Bangalore batting team      0.0
Sunrisers Hyderabad batting team              0.0
Chennai Super Kings bowling team              0.0
Delhi Capitals bowling team                   0.0
Gujarat Lions bowling team                    0.0
Kings XI Punjab bowling team                  0.0
Kolkata Knight Riders bowling team            0.0
Mumbai Indians bowling team                   0.0
Pune Warriors bowling team                    0.0
Rajasthan Royals bowling team                 0.0
Royal Challengers Bangalore bowling team      1.0
Sunrisers Hyderabad bowling team              0.0
team1                                         8.0
team2                                         2.0
toss_winner                                   2.0
toss_decision                                 1.0
powerplay_runs                               57.0
powerplay_wickets                             2.0
powerplay_run_rate                            9.5
final_runs                                  192.0
Name: 38, dtype: float64

In [557]:
y=final_data["final_runs"]

In [558]:
final_data.columns

Index(['inning', 'Chennai Super Kings batting team',
       'Delhi Capitals batting team', 'Gujarat Lions batting team',
       'Kings XI Punjab batting team', 'Kolkata Knight Riders batting team',
       'Mumbai Indians batting team', 'Pune Warriors batting team',
       'Rajasthan Royals batting team',
       'Royal Challengers Bangalore batting team',
       'Sunrisers Hyderabad batting team', 'Chennai Super Kings bowling team',
       'Delhi Capitals bowling team', 'Gujarat Lions bowling team',
       'Kings XI Punjab bowling team', 'Kolkata Knight Riders bowling team',
       'Mumbai Indians bowling team', 'Pune Warriors bowling team',
       'Rajasthan Royals bowling team',
       'Royal Challengers Bangalore bowling team',
       'Sunrisers Hyderabad bowling team', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'powerplay_runs', 'powerplay_wickets',
       'powerplay_run_rate', 'final_runs'],
      dtype='object')

In [559]:
model.score(X,Y)

0.31482159963111545